### ISSUE TITLE
Issue on image_downloading line 90

### ISSUE THREAD

**Issue by pineapplelogic174** [andolg/satellite-imagery-downloader#2]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/satellite-imagery-downloader/src/image_downloading.py", line 90, in build_row
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]
ValueError: could not broadcast input array from shape (1,1,3) into shape (1,1,4)
Saved as img_20230327151245.png

**Comment by andolg** [comment]
`ValueError: could not broadcast input array from shape (1,1,3) into shape (1,1,4)` means that you are downloading tiles with only 3 channels, while the output image has 4 channels. To solve this, you just need to use `"jpg"` (actually, anything except `"png"`) as `"tile_format"`. This setting changes both the number of channels in the output image and the tile decoding mode.
