### ISSUE TITLE
Not able to download a specific request image

### ISSUE THREAD

**Issue by hemantsingh11** [andolg/satellite-imagery-downloader#5]
Top-left corner: 38.49340041300801, 34.41634574663586
Bottom-right corner: 33.090940428830905, 41.067412310793216
Zoom level: 12

error:

Exception in thread Thread-59 (build_row):
Traceback (most recent call last):
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
Exception in thread Thread-65 (build_row):
Exception in thread Thread-62 (build_row):
Traceback (most recent call last):
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
Exception in thread Thread-67 (build_row):
Exception in thread Thread-61 (build_row):
Traceback (most recent call last):
Exception in thread Thread-73 (build_row):
    self.run()
Exception in thread Thread-66 (build_row):
Exception in thread Thread-74 (build_row):
Traceback (most recent call last):
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
Exception in thread Thread-77 (build_row):
Traceback (most recent call last):
Exception in thread Thread-76 (build_row):
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
Traceback (most recent call last):
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
Traceback (most recent call last):
Exception in thread Thread-58 (build_row):
Exception in thread Thread-60 (build_row):
Traceback (most recent call last):
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
Exception in thread Thread-64 (build_row):
Traceback (most recent call last):
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
Traceback (most recent call last):
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
Traceback (most recent call last):
Exception in thread Thread-71 (build_row):
Exception in thread Thread-63 (build_row):
Traceback (most recent call last):
    self.run()
    self.run()
Exception in thread Thread-69 (build_row):
Traceback (most recent call last):
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
Exception in thread Thread-75 (build_row):
    self.run()
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
Traceback (most recent call last):
    self.run()
Exception in thread Thread-70 (build_row):
Exception in thread Thread-72 (build_row):
Traceback (most recent call last):
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
    self.run()
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
Traceback (most recent call last):
    self.run()
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
Traceback (most recent call last):
Exception in thread Thread-68 (build_row):
    self.run()
    self.run()
Traceback (most recent call last):
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
Traceback (most recent call last):
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self.run()
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self.run()
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
    self.run()
    self._target(*self._args, **self._kwargs)
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]   
Exception in thread Thread-51 (build_row):
    self.run()
    self._target(*self._args, **self._kwargs)
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
    self.run()
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
    self._target(*self._args, **self._kwargs)
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
    self.run()
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
Traceback (most recent call last):
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
    self._target(*self._args, **self._kwargs)
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
Exception in thread Thread-33 (build_row):
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
TypeError: 'NoneType' object is not subscriptable
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]
Exception in thread Thread-52 (build_row):
Exception in thread Thread-36 (build_row):
Exception in thread Thread-50 (build_row):
Exception in thread Thread-34 (build_row):
Exception in thread Thread-53 (build_row):
Exception in thread Thread-30 (build_row):
Exception in thread Thread-57 (build_row):
    self._target(*self._args, **self._kwargs)
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]   
    self.run()
Exception in thread Thread-56 (build_row):
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]   
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
TypeError: 'NoneType' object is not subscriptable
    self._target(*self._args, **self._kwargs)
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
TypeError: 'NoneType' object is not subscriptable
Exception in thread Thread-35 (build_row):
Traceback (most recent call last):
    self.run()
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
Exception in thread Thread-55 (build_row):
Traceback (most recent call last):
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]   
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
Exception in thread Thread-31 (build_row):
    self.run()
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]   
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
Traceback (most recent call last):
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
    self.run()
Exception in thread Thread-37 (build_row):
    self._target(*self._args, **self._kwargs)
Exception in thread Thread-32 (build_row):
Traceback (most recent call last):
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
Traceback (most recent call last):
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
Exception in thread Thread-38 (build_row):
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]   
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]   
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
Traceback (most recent call last):
Exception in thread Thread-54 (build_row):
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
    self.run()
    self.run()
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]   
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]   
Traceback (most recent call last):
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
Traceback (most recent call last):
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
TypeError: 'NoneType' object is not subscriptable
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self.run()
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]   
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]   
    self.run()
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]   
    self.run()
    self.run()
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]   
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'NoneType' object is not subscriptable
    self.run()
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
    self.run()
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
    self._target(*self._args, **self._kwargs)
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
TypeError: 'NoneType' object is not subscriptable
    self.run()
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
TypeError: 'NoneType' object is not subscriptable
    self._target(*self._args, **self._kwargs)
TypeError: 'NoneType' object is not subscriptable
    self._target(*self._args, **self._kwargs)
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self.run()
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
    self._target(*self._args, **self._kwargs)
TypeError: 'NoneType' object is not subscriptable
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]   
TypeError: 'NoneType' object is not subscriptable
    self._target(*self._args, **self._kwargs)
TypeError: 'NoneType' object is not subscriptable
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
    self.run()
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]   
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
TypeError: 'NoneType' object is not subscriptable
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
    self._target(*self._args, **self._kwargs)
    self.run()
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]   
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]   
TypeError: 'NoneType' object is not subscriptable
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
Traceback (most recent call last):
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]   
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
TypeError: 'NoneType' object is not subscriptable
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]   
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]   
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]   
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
    self._target(*self._args, **self._kwargs)
TypeError: 'NoneType' object is not subscriptable
    self._target(*self._args, **self._kwargs)
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
TypeError: 'NoneType' object is not subscriptable
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
    self.run()
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]   
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]   
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
TypeError: 'NoneType' object is not subscriptable
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]   
    self.run()
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]   
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
TypeError: 'NoneType' object is not subscriptable
TypeError: 'NoneType' object is not subscriptable
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
TypeError: 'NoneType' object is not subscriptable
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
TypeError: 'NoneType' object is not subscriptable
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]   
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
TypeError: 'NoneType' object is not subscriptable
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
TypeError: 'NoneType' object is not subscriptable
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]   
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]   
    self._target(*self._args, **self._kwargs)
  File "C:\Users\iamhe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
TypeError: 'NoneType' object is not subscriptable
TypeError: 'NoneType' object is not subscriptable
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]   
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]   
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
TypeError: 'NoneType' object is not subscriptable
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
TypeError: 'NoneType' object is not subscriptable
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]
TypeError: 'NoneType' object is not subscriptable
TypeError: 'NoneType' object is not subscriptable
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]
  File "e:\Fall 23\DS549 Sparl ML\satellite-imagery-downloader\src\image_downloading.py", line 90, in build_row
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    img[i_y_l:i_y_r, i_x_l:i_x_r] = tile[cr_y_l:cr_y_r, cr_x_l:cr_x_r]
TypeError: 'NoneType' object is not subscriptable
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
TypeError: 'NoneType' object is not subscriptable

**Comment by andolg** [comment]
Hi, thanks a lot for the report. The image you were trying to download looks like this:

![img1](https://github.com/andolg/satellite-imagery-downloader/assets/82101056/6ab1b3d9-0f54-4c8f-a98c-8ac46c31ce55)
![img2](https://github.com/andolg/satellite-imagery-downloader/assets/82101056/4a4699b4-483c-4400-8d96-e2024ecca86e)

The black parts are the tiles that cause the errors. Some areas (like large bodies of water) just don't have tile coverage at high zoom levels.

For now, I've updated the code so that it skips unavailable tiles and leaves empty space on the image.
